import{i as a,S,a as x}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();const y=document.querySelector(".gallery");y.style.display="grid";y.style.gridTemplateColumns="repeat(auto-fill, minmax(300px, 1fr))";y.style.gap="16px";y.style.padding="16px";function I(r,o){if(!Array.isArray(r)){a.error({title:"Error",message:"displayImages expects an array but received:"+typeof r});return}const l=document.getElementById("imageResults");o===1&&(l.innerHTML=""),r.forEach(e=>{const t=document.createElement("a");t.classList.add("image-card"),t.href=e.largeImageURL,t.innerHTML=`
            
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
            
            <div class="info">
                <p><b>Likes:</b> ${e.likes}</p>
                <p><b>Views:</b> ${e.views}</p>
                <p><b>Comments:</b> ${e.comments}</p>
                <p><b>Downloads:</b> ${e.downloads}</p>
            </div>`,l.appendChild(t);const s=t;s.style.position="relative",s.style.overflow="hidden",s.style.borderRadius="8px",s.style.boxShadow="0 2px 8px rgba(0, 0, 0, 0.1)";const n=t.querySelector(".info");n.style.position="absolute",n.style.bottom="0",n.style.left="0",n.style.right="0",n.style.padding="8px",n.style.background="rgba(0, 0, 0, 0.6)",n.style.color="#fff",n.style.fontSize="14px"}),new S(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function q(){const r=document.getElementById("imageResults");r.innerHTML=""}const g=document.querySelector(".loader");function R(){g.classList.remove("hidden")}function $(){g.classList.add("hidden")}const P="44406774-b6929e0ee65f9835201f12742";async function h(r,o=1,l,i,e){const t="https://pixabay.com/",s="api/",n=new URLSearchParams({key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}),E=`${t}${s}?${n}`;try{R();const f=(await x.get(E)).data;f.hits.length===0?(o===1&&q(),a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),i()):(I(f.hits,o),f.totalHits>o*15?l():(i(),e()))}catch{a.error({title:"Error",message:"An error occurred while fetching images. Please try again!"}),i()}finally{$()}}let u=1,d="";const T=document.querySelector("form"),p=document.querySelector("input");document.querySelector("button[type=submit]");const m=document.querySelector("button[type=button]"),b=document.createElement("style");b.innerHTML=`
.hidden {
    display: none;
}
`;document.head.appendChild(b);function L(){m.classList.remove("hidden")}function c(){m.classList.add("hidden"),console.log("Кнопка схована:",m.classList.contains("hidden"))}function w(){a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}function A(){const r=document.querySelector(".image-card");if(r){const o=r.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}c();T.addEventListener("submit",async r=>{if(r.preventDefault(),d=p.value.trim(),d==="")c(),a.error({title:"Error",message:"Поле пошуку не може бути порожнім"});else{u=1,c();try{await h(d,u,L,c,w),p.value=""}catch(o){a.error({title:"Error",message:"An error occurred while fetching images. Please try again!"}),console.error("Error fetching images:",o)}}});m.addEventListener("click",async()=>{u++;try{await h(d,u,L,c,w),A()}catch(r){a.error({title:"Error",message:"An error occurred while fetching more images. Please try again!"}),console.error("Error fetching more images:",r)}});
//# sourceMappingURL=commonHelpers.js.map
